### ISSUE TITLE
使用HSFace10K训练无法复现论文中的精度

### ISSUE THREAD

**Issue by GukehAn** [HaiyuWu/Vec2Face#1]
你好，我按照文中的配置使用HSFace10K训练人脸模型，最高平均精度为89.94。请问是否有一些文中没有提及的配置？

**Comment by HaiyuWu** [comment]
这是我使用的设置，如果您使用的是[SOTA-Face-Recognition-Train-and-Test](https://github.com/HaiyuWu/SOTA-Face-Recognition-Train-and-Test) 这个库，应该是没有问题的。
···
from easydict import EasyDict

config = EasyDict()

config.prefix = "arcface-r50-hsface10k"
config.head = "arcface"
config.input_size = [112, 112]
config.embedding_size = 512
config.depth = "50"
config.batch_size = 128
config.weight_decay = 5e-4
config.lr = 0.1
config.momentum = 0.9
config.epochs = 26
config.margin = 0.5
config.fp16 = True
config.sample_rate = 1.0
config.num_ims = 500000
config.reduce_lr = [12, 20, 24]
config.train_source = "./vec2face_datasets/hsface10k.lmdb"
config.val_list = ["lfw", "cfp_fp", "agedb_30", "calfw", "cplfw"]
config.mask = None
config.augment = True
config.mode = "se"
··

**Comment by HaiyuWu** [comment]
这是我最近跑的[log](https://github.com/user-attachments/files/17069122/training.log)文件，精度应该是没问题的。可能会上下浮动一些但是不至于不到90。另外提醒一下，您需要在data loader里加RandomErasing。具体操作见 [#fr-model-training](https://github.com/HaiyuWu/Vec2Face?tab=readme-ov-file#fr-model-training).
