### ISSUE TITLE
About pca getting new id feature

### ISSUE THREAD

**Issue by biburger** [HaiyuWu/Vec2Face#10]
Thanks for your work! I'm interested in the PCA random identity vector generation in your project. Could you share your approach or code for this part? I'd really appreciate it.

**Comment by HaiyuWu** [comment]
> Thanks for your work! I'm interested in the PCA random identity vector generation in your project. Could you share your approach or code for this part? I'd really appreciate it.

Sure, this is the code for PCA sampling. You need to replace the ```path/of/your/extracted/feature_file``` with the file path that contains all the features.
```python
import numpy as np
from sklearn.decomposition import PCA

def generate_normalized_vectors(num, dim):
    identity = np.load("/path/of/your/extracted/feature_file")
    pca_id = PCA(n_components=512)
    pca_id.fit(identity)

    transformed_data = pca_id.transform(identity)
    mean = np.mean(transformed_data, axis=0)
    cov = np.cov(transformed_data, rowvar=False)
    new_samples_pca_space = np.random.multivariate_normal(mean, cov, size=num_vectors)
    new_ids = pca_id.inverse_transform(new_samples_pca_space).astype('float32')
```
