### ISSUE TITLE
how to use prepare_training_set.py?

### ISSUE THREAD

**Issue by ericyq** [HaiyuWu/Vec2Face#3]
Can you give your an example

**Comment by HaiyuWu** [comment]
1. Making sure you have two .txt files that store the paths of images and their features. Using [file_path_extractor.py](https://github.com/HaiyuWu/SOTA-Face-Recognition-Train-and-Test/blob/main/file_path_extractor.py) to collect these paths.
2. Using [identity_label_collection.py](https://github.com/HaiyuWu/Vec2Face/blob/main/scripts/identity_label_collection.py) to get and save the labels. Note that, labels actually are not needed in this work. I keep them for possible future work. If your dataset is not formed as *id/image*, please modify this code to get correct labels.
3. Then you have everything ready for creating a .lmdb training set.
```
python prepare_training_set.py \
-im image/path/.txt \
-f feature/path/.txt \
-l label/path/.txt \
-d destination \
-n file/name
```

**Comment by ericyq** [comment]
Which model to extracte feature?

**Comment by HaiyuWu** [comment]
You can use any FR packages to extract the feature. I am using [SOTA-Face-Recognition-Train-and-Test](https://github.com/HaiyuWu/SOTA-Face-Recognition-Train-and-Test?tab=readme-ov-file#feature-extraction). You can follow the instruction there to extract the image features.

**Comment by HaiyuWu** [comment]
You can using any of them in the model zoo. I am using ArcFace-R100 trained with glint360k dataset.
