### ISSUE TITLE
使用参考图像生成样本

### ISSUE THREAD

**Issue by yeluohuazhifou** [HaiyuWu/Vec2Face#5]
想生成指定id不同姿态不同表情的图片，但是发现很多生成的图片看起来都差不多，有没有参数可以控制类内变化更大一些呢

**Comment by yeluohuazhifou** [comment]
传入pose_model，发现生成的图片pose变化也不是很大；很多也都是正脸图像

**Comment by yeluohuazhifou** [comment]
> 想生成指定id不同姿态不同表情的图片，但是发现很多生成的图片看起来都差不多，有没有参数可以控制类内变化更大一些呢

使用的都是人脸识别中处理好的图像。生成的图像质量确实很好，但是就是正脸易于识别的图像占比太多了

**Comment by HaiyuWu** [comment]
> 想生成指定id不同姿态不同表情的图片，但是发现很多生成的图片看起来都差不多，有没有参数可以控制类内变化更大一些呢

用更大的epsillion可以提供更多的variation [image_generation_with_reference.py#L144](https://github.com/HaiyuWu/Vec2Face/blob/7ae1bc7f4982926cbbbb7bab604e83e8a6f69d28/image_generation_with_reference.py#L144)。

**Comment by HaiyuWu** [comment]
> 使用的都是人脸识别中处理好的图像。生成的图像质量确实很好，但是就是正脸易于识别的图像占比太多了

您可以试着用更大的pose angle，比如我用了60和85。这里有一个技巧，如果您想有比较好的pose输出，将quality设置到26以上，虽然会让生成时间变长，但是可以保证图片质量和pose质量。

**Comment by yeluohuazhifou** [comment]
> > 使用的都是人脸识别中处理好的图像。生成的图像质量确实很好，但是就是正脸易于识别的图像占比太多了
> 
> 您可以试着用更大的pose angle，比如我用了60和85。这里有一个技巧，如果您想有比较好的pose输出，将quality设置到26以上，虽然会让生成时间变长，但是可以保证图片质量和pose质量。

太棒了，我试一下
