### ISSUE TITLE
could you provide the multi-threaded code about the image generation

### ISSUE THREAD

**Issue by ericyq** [HaiyuWu/Vec2Face#7]
>>>python image_generation_with_reference.py \
--image_file "path/of/the/image/file or folder" \
--model_weights weights/vec2face_generator.pth \
--batch_size 5 \
--example 10 \
--name images-of-references

the generation of the images is far too slow

**Comment by HaiyuWu** [comment]
I have updated the code. It does not include the AttrOP process, so the speed is way faster but there is no guarantee for good image quality (it is due to the low image resolution in the training set).
You can further use DataParallel to use multiple gpus for faster inference.
